Repository LetsGitGoing-Labs/BookHuddle, pull requests merged in 2018-03, with the labels that each got.

#2 Set up continuous integration with testing
  .travis.yml
  package-lock.json
  package.json
  server/index.js
Labels: in progress

#10 Feat/client skeleton closes #7
  .babelrc
  .gitignore
  client/dist/bundle.js
  client/dist/index.html
  client/dist/styles.css
  client/src/components/App.jsx
  client/src/components/Home.jsx
  client/src/components/about.jsx
  client/src/components/create-club.jsx
  client/src/components/dashboard.jsx
  client/src/components/faq.jsx
  client/src/components/login.jsx
  client/src/components/logout.jsx
  client/src/components/profile.jsx
  client/src/components/signup.jsx
  client/src/index.jsx
  package-lock.json
  package.json
  webpack.config.js
Labels: in progress

#11 Deploy app to Heroku
  Procfile
  client/dist/bundle.js
  client/src/components/about.jsx
  client/src/components/home.jsx
Labels: in progress

#12 signup login club forms created
  client/dist/index.html
  client/dist/styles.css
  client/src/components/create-club.jsx
  client/src/components/login.jsx
  client/src/components/signup.jsx
  package.json
Labels: in progress

#13 set up knex connection and schema
  .env
  database/index-psql.js
  helpers/knex.js
  package.json
Labels: in progress

#15 Feat/client static pages- homepage
  client/dist/index.html
  client/dist/styles.css
  client/src/components/App.jsx
  client/src/components/book.jsx
  client/src/components/home.jsx
  client/src/components/main-navbar.jsx
Labels: in progress

#16 Set up Amazon API helper functions for backend - closes #14
  .env
  client/dist/bundle.js
  package.json
  server/api-helpers/amazon-helpers.js
  server/index.js
Labels: in progress

#17 Add heroku-postbuild script
  .gitignore
  Procfile
  package.json
Labels: in progress

#21 facebook auth
  client/dist/index.html
  client/src/components/login.jsx
  package.json
Labels: in progress

#22 Test/client auth routes #20
  client/src/components/App.jsx
  client/src/components/login.jsx
  server/index.js
  server/spec/spec.js
Labels: in progress

#23 add addUser fn to queries.js file, some new code in server/index.js
  knexHelpers/index.js
  knexHelpers/queries.js
  server/index.js
Labels: in progress

#24 Add api call to createaclub
  client/src/components/create-club.jsx
Labels: in progress

#27 add user and add club
  knexHelpers/index.js
  knexHelpers/queries.js
  server/index.js
Labels: in progress

#30 Add ability to save user and club from frontend to db
  client/src/components/create-club.jsx
  client/src/components/login.jsx
  client/src/components/signup.jsx
  env
  knexHelpers/queries.js
  server/index.js
Labels: in progress

#32 Create skeleton for dashboard and minor fixes in server
  client/dist/index.html
  client/src/components/book-list-dashboard.jsx
  client/src/components/clubs-list-dashboard.jsx
  client/src/components/dashboard.jsx
  client/src/components/login.jsx
  client/src/components/meeting-list-dashboard.jsx
  server/index.js
Labels: in progress

#33 Fix/client file structure
  client/dist/index.html
  client/src/components/App.jsx
  client/src/components/home.jsx
  client/src/components/main-navbar.jsx
  client/src/index.jsx
  client/src/styles/main.css
  client/src/styles/reset.css
  package.json
  server/index.js
  webpack.config.js
Labels: in progress

#35 Create modals for login signup
  client/src/components/App.jsx
  client/src/components/dashboard.jsx
  client/src/components/login-modal.jsx
  client/src/components/login.jsx
  client/src/components/main-navbar.jsx
  client/src/components/signup.jsx
  client/src/styles/main.css
  package.json
Labels: in progress

#36 add Club skeleton and children components
  client/dist/styles.css
  client/src/components/App.jsx
  client/src/components/club.jsx
  client/src/components/meeting.jsx
  client/src/components/meetinglist.jsx
  client/src/styles/main.css
  knexHelpers/index.js
Labels: in progress

#37 begin pulling data from API and db into dashboard component
  client/src/components/book-list-dashboard.jsx
  client/src/components/clubs-list-dashboard.jsx
  client/src/components/dashboard.jsx
  client/src/components/meeting-list-dashboard.jsx
  client/src/index.jsx
  knexHelpers/index.js
  knexHelpers/queries.js
  package.json
  server/index.js
Labels: in progress

#43 Add login post req for login
  client/src/components/login.jsx
Labels: in progress

#45 login returns object db retrieves user
  client/src/components/login.jsx
  client/src/styles/main.css
  knexHelpers/queries.js
  server/index.js
Labels: in progress

#51 reorganize the database related files under the database folder
  database/index-mongodb.js
  database/index-psql.js
  database/index-sql.js
  database/index.js
  database/knex.js
  database/queries.js
  server/index.js
Labels: in progress

#52 converted clubform to modal
  client/src/components/create-club.jsx
Labels: in progress

#53 Pass user from login/signup to dashboard and add retrieveUser function
  client/src/components/create-club.jsx
  client/src/components/dashboard.jsx
  client/src/components/login-modal.jsx
  client/src/components/login.jsx
  client/src/components/signup.jsx
  database/queries.js
  server/index.js
Labels: in progress

#56 Feat/client signin modal closes #44
  client/src/components/App.jsx
  client/src/components/login-modal.jsx
  client/src/components/login.jsx
  client/src/components/main-navbar.jsx
  client/src/components/signup.jsx
  client/src/styles/main.css
Labels: in progress

#55 Create yourClubList subcomponent that redirects to club page
  client/src/components/book-list-dashboard.jsx
  client/src/components/club.jsx
  client/src/components/clubs-list-dashboard.jsx
  client/src/components/create-club.jsx
  client/src/components/dashboard.jsx
  client/src/components/meeting-list-dashboard.jsx
  client/src/components/your-club-list-dashboard.jsx
  client/src/styles/main.css
  database/index.js
  server/api-helpers/amazon-helpers.js
  server/index.js
Labels: in progress

#75 Fix/client refactor login handling #70
  client/src/components/App.jsx
  client/src/components/dashboard-nav.jsx
  client/src/components/dashboard.jsx
  client/src/components/home.jsx
  client/src/components/login-modal.jsx
  client/src/components/login.jsx
  client/src/components/main-navbar.jsx
  client/src/components/signup.jsx
Labels: in progress

#76 Clean up server, delete fb auth, styling on dashboard - closes #76
  client/src/components/create-club.jsx
  client/src/components/dashboard.jsx
  client/src/styles/main.css
  server/index.js
Labels: in progress

#77 Feat/client dashboard club rendering
  client/src/components/clubs-list-dashboard.jsx
  client/src/components/create-club.jsx
  client/src/components/dashboard-nav.jsx
  client/src/components/dashboard.jsx
  client/src/components/your-club-list-dashboard.jsx
Labels: in progress

#78 Re-configure app for Heroku deployment with db/api
  database/index.js
  database/knex.js
Labels: in progress

#92 Feat/client Nested routes created
  client/dist/styles.css
  client/src/components/App.jsx
  client/src/components/book-list-dashboard.jsx
  client/src/components/club.jsx
  client/src/components/create-club.jsx
  client/src/components/dashboard-nav.jsx
  client/src/components/dashboard-navbar.jsx
  client/src/components/dashboard-routing.jsx
  client/src/components/dashboard.jsx
  client/src/components/logout.jsx
  client/src/components/meeting-list-dashboard.jsx
  client/src/components/your-club-list-dashboard.jsx
Labels: PR submitted

#93 fix login object returned to client, refactor get clubs to correctly handle status codes
  database/queries.js
  server/index.js
Labels: PR submitted, bug

#94 Create unit testing suite for server and database
  client/dist/index.html
  client/src/components/dashboard.jsx
  database/index.js
  database/queries.js
  package.json
  server/api-helpers/amazon-helpers.js
  server/index.js
  server/spec/spec.js
Labels: PR submitted

#100 Feat/client components
  .travis.yml
  client/src/components/App.jsx
  client/src/components/clubs/club.jsx
  client/src/components/dashboard-navbar.jsx
  client/src/components/dashboard-routing.jsx
  client/src/components/dashboard.jsx
  client/src/components/dashboard/create-club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  client/src/components/dashboard/panel-clubs.jsx
  client/src/components/dashboard/panel-meetings.jsx
  client/src/components/dashboard/panel-suggested.jsx
  client/src/components/home/about.jsx
  client/src/components/home/home.jsx
  client/src/components/home/logout.jsx
  client/src/components/home/profile.jsx
  client/src/components/navigation/dashboard-navbar.jsx
  client/src/components/navigation/main-navbar.jsx
  client/src/components/navigation/sidebar.jsx
  client/src/components/signin/login-modal.jsx
  client/src/components/signin/login.jsx
  client/src/components/signin/signup.jsx
  client/src/styles/dashboard.css
  client/src/styles/style.css
Labels: PR submitted

#101 Re-configure client/server HTTP requests with GraphQL
  client/src/components/App.jsx
  client/src/components/dashboard/create-club.jsx
  client/src/components/dashboard/dashboard.jsx
  server/api-helpers/amazon-helpers.js
  server/index.js
  server/spec/spec.js
Labels: PR submitted

#104 Feat/client clubpage build
  client/dist/index.html
  client/src/components/clubs/club.jsx
  client/src/components/clubs/create-meeting.jsx
  client/src/components/clubs/upcoming.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  client/src/components/dashboard/panel-clubs.jsx
  client/src/components/dashboard/panel-meetings.jsx
  client/src/components/dashboard/pretty-date.jsx
  client/src/components/navigation/club-nav.jsx
  client/src/components/navigation/sidebar.jsx
  client/src/styles/club.css
  package.json
Labels: PR submitted

#110 Refactor to have complete user object
  client/src/components/App.jsx
  client/src/components/home/home.jsx
  client/src/components/signin/signup.jsx
  database/index.js
  database/queries.js
Labels: PR submitted

#117 added retreiveClubByName and refactored error handling on retreiveUser
  database/knex.js
  database/queries.js
  package.json
  server/index.js
Labels: PR submitted

#118 Feat/client searchclubs
  client/src/components/App.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  client/src/components/dashboard/panel-search-results.jsx
  client/src/components/dashboard/searchbar.jsx
  client/src/components/navigation/dashboard-navbar.jsx
Labels: PR submitted

#120 Trivia component and autocomplete signup
  client/MockQuestions/questions.js
  client/src/components/App.jsx
  client/src/components/signin/signup.jsx
  client/src/components/trivia-ask.jsx
  client/src/components/trivia-curplayers.jsx
  client/src/components/trivia-host.jsx
  client/src/components/trivia-hostpage.jsx
  client/src/components/trivia-join.jsx
  client/src/components/trivia-main.jsx
  client/src/components/trivia-players.jsx
  client/src/components/trivia-qs.jsx
  client/src/components/trivia-score.jsx
  client/src/styles/trivia.css
  package.json
  server/index.js
Labels: PR submitted

#127 Fix login glitch, finish getNearClubs function, add button to club.jsx
  client/src/components/App.jsx
  client/src/components/clubs/club.jsx
  client/src/components/dashboard/dashboard.jsx
  server/index.js
Labels: PR submitted

#129 Autocomplete on create club form location
  client/src/components/dashboard/create-club.jsx
  client/src/components/signin/signup.jsx
  client/src/components/trivia-ask.jsx
  client/src/components/trivia-main.jsx
  client/src/components/trivia-qs.jsx
  client/src/components/trivia-score.jsx
  client/src/styles/trivia.css
Labels: PR submitted

#132 Finish creating functionality for adding user to club
  client/src/components/App.jsx
  client/src/components/clubs/club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  client/src/components/home/home.jsx
  database/queries.js
  server/index.js
Labels: PR submitted

#154 Add user id to create club and create meeting form data
  client/src/components/clubs/create-meeting.jsx
  client/src/components/dashboard/create-club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
Labels: PR submitted

#157 Update club table to store club_location (instead of club_city & club_state_province). ALSO now storing admin userID
  database/index.js
  database/queries.js
  server/index.js
Labels: PR submitted

#159 installed eslint and changed location inputs closes #106 #137
  .eslintrc.js
  client/MockQuestions/questions.js
  client/src/components/App.jsx
  client/src/components/clubs/club.jsx
  client/src/components/clubs/create-meeting.jsx
  client/src/components/clubs/upcoming.jsx
  client/src/components/dashboard/create-club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  client/src/components/dashboard/panel-clubs-near-you.jsx
  client/src/components/dashboard/panel-clubs.jsx
  client/src/components/dashboard/panel-meetings.jsx
  client/src/components/dashboard/panel-search-results.jsx
  client/src/components/dashboard/panel-suggested.jsx
  client/src/components/dashboard/pretty-date.jsx
  client/src/components/dashboard/searchbar.jsx
  client/src/components/home/about.jsx
  client/src/components/home/home.jsx
  client/src/components/home/logout.jsx
  client/src/components/home/profile.jsx
  client/src/components/navigation/club-nav.jsx
  client/src/components/navigation/dashboard-navbar.jsx
  client/src/components/navigation/main-navbar.jsx
  client/src/components/navigation/sidebar.jsx
  client/src/components/signin/login-modal.jsx
  client/src/components/signin/login.jsx
  client/src/components/signin/signup.jsx
  client/src/components/trivia-ask.jsx
  client/src/components/trivia-curplayers.jsx
  client/src/components/trivia-host.jsx
  client/src/components/trivia-hostpage.jsx
  client/src/components/trivia-join.jsx
  client/src/components/trivia-main.jsx
  client/src/components/trivia-players.jsx
  client/src/components/trivia-qs.jsx
  client/src/components/trivia-score.jsx
  client/src/index.jsx
  database/index.js
  database/queries.js
  package.json
  server/api-helpers/amazon-helpers.js
  server/index.js
  server/spec/spec.js
  webpack.config.js
Labels: PR submitted

#160 Create server/db route for passing user/club/meetings data to dashboard - closes #136
  client/src/components/App.jsx
  client/src/components/clubs/club.jsx
  database/queries.js
  server/index.js
Labels: PR submitted

#163 changed Id to ID in create club
  client/src/components/clubs/create-meeting.jsx
  client/src/components/dashboard/create-club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/trivia-ask.jsx
  client/src/components/trivia-players.jsx
  server/index.js
Labels: PR submitted

#164 Feat/client newpages
  client/src/components/dashboard/create-club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  client/src/components/dashboard/panel-meetings.jsx
  client/src/components/meetings/meeting.jsx
  client/src/components/navigation/meeting-nav.jsx
  webpack.config.js
Labels: PR submitted

#167 Dashboard dynamically renders user data on load, refactor signup/login
  client/src/components/App.jsx
  client/src/components/clubs/club.jsx
  client/src/components/dashboard/dashboard-routing.jsx
  client/src/components/dashboard/dashboard.jsx
  database/index.js
  database/queries.js
  server/index.js
Labels: PR submitted

#168 debugging version
  database/queries.js
  database/seed/books.JSON
  database/seed/clubs.JSON
  database/seed/meetings.JSON
  database/seed/seed.js
  database/seed/users.JSON
Labels: PR submitted
